version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: notes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notes_app

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always


  notes-server:
    build: ./Server
    container_name: notes-server
    depends_on:
      - mysql
    environment:
      PORT: 5000
      JWT_SECRET: my-secret-keyokay
      DB_HOST: mysql
      DB_USER: root 
      DB_PASSWORD: rootpassword
      DB_NAME: notes_app
    ports:
      - "5000:5000"
    restart: always


  notes-client:
    build: ./Client
    container_name: notes-client
    depends_on:
      - notes-server
    ports:
      - "80:80"
    restart: always


volumes:
  mysql_data:
