apiVersion: v1
kind: Service

metadata:
  name: notes-server
  namespace: notes-app

spec:
  type: ClusterIP
  selector:
    app: notes-server
  ports:
  - port: 5000
    targetPort: 5000
    name: http
