apiVersion: v1
kind: ConfigMap

metadata:
  name: notes-configs
  namespace: notes-app

data:
  DB_HOST: "10.0.2.139"
  DB_PORT: "3306"
  DB_NAME: "notes_app"
  PORT: "5000"     
  NODE_ENV: "production"

